sudo: required
services:
  - docker

before_install:
  - docker build -t ananj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ananj/react-test npm run test -- --coverage

after_success:
  - docker build -t ananj/webapp-client ./client
  - docker build -t ananj/webapp-nginx  ./nginx
  - docker build -t ananj/webapp-server ./server
  - docker build -t ananj/webapp-worker ./worker
  # Log in to the Docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to the DockerHub.
  # echo "$DOCKER_PASSWORD" ==> retrieve Docker password from env variable
  # | to emit the output from echo "$DOCKER_PASSWORD" to the next command
  - docker push ananj/webapp-client
  - docker push ananj/webapp-nginx
  - docker push ananj/webapp-server
  - docker push ananj/ananj/webapp-worker